platformName: Android
#模拟器
platformVersion: 7.1.1
deviceName: 192.168.1.3:5555

#mx4真机
#platformVersion: 5.1
#udid: 750BBKL22GDN
#deviceName: MX4

appname: kaoyan3.1.0.apk
noReset: False
#unicodeKeyboard: True
#resetKeyboard: True
appPackage: com.baidu.homework
appActivity: com.baidu.homework.activity.init.InitActivity
ip: 127.0.0.1
port: 4723